language: php

sudo: false

services:
  - mysql

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - |
    if [ -z $CLASSICPRESS ]; then
      bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION;
    else
      bash tests/bin/install-cp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION;
    fi
  - bash tests/bin/install-wp-cli.sh

script:
  - make lint:php
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/behat

after_script:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.4
      env: WP_VERSION=master WP_MULTISITE=1
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache
